# Generated by Django 5.2.7 on 2025-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('displayName', models.CharField(max_length=100)),
                ('contactDetails', models.CharField(max_length=100)),
                ('userSchedule', models.JSONField(default=set)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=100)),
                ('sectionName', models.CharField(max_length=100)),
                ('sectionDetails', models.CharField(max_length=200)),
                ('maxSize', models.IntegerField(default=2)),
                ('studentList', models.ManyToManyField(to='groupme_app.user')),
            ],
        ),
    ]
